### ISSUE TITLE
PDBError: Coordinate mismatch in model 1

### ISSUE THREAD

**Issue by dimkol94** [Valdes-Tresanco-MS/gmx_MMPBSA#13] opened 2021-01-10 20:49 UTC
Hi,

I am running a heterodimeric membrane protein (2 chains) with a ligand. I have tried with both a *.gro and a *.tpr file as input.
I installed AmberTools20 with conda and then did pip install gmx_MMPBSA in the conda environment. This is after I realised that Amber18 package does not work with this tool (python3 issue raised before here)
I am using this command:

gmx_MMPBSA -i MMPBSA_input -cs ../pr_200ns.tpr -ci index.ndx -cg 1 13 -ct ../pr_200ns_whole_nojump_center_rotxy-transxy.xtc --overwrite

Can you provide more info as to what is wrong with my files? The error message I am receiving is not very enlightening as to what the problem is...

OUTPUT:

Loading and checking parameter files for compatibility...

cpptraj found! Using /sansom/s152/bras4549/anaconda3/envs/AmberTools20/bin/cpptraj
gmx found! Using /sbcb/packages/opt/Linux_x86_64/gromacs/2020.3_GCC6.2_CUDA10.1.AVX2/bin/gmx
tleap found! Using /sansom/s152/bras4549/anaconda3/envs/AmberTools20/bin/tleap
parmchk2 found! Using /sansom/s152/bras4549/anaconda3/envs/AmberTools20/bin/parmchk2
sander found! Using /sansom/s152/bras4549/anaconda3/envs/AmberTools20/bin/sander
Normal Complex: Save group 1_13 in index.ndx (gromacs index) file as _GMXMMPBSA_COM.pdb
Clear normal complex trajectories...
Using receptor structure from complex to make amber topology
Normal Complex: Save group 1 in _GMXMMPBSA_COM_index.ndx (gromacs index) file as _GMXMMPBSA_REC.pdb
Using ligand structure from complex to make amber topology
Save group 13 in _GMXMMPBSA_COM_index.ndx (gromacs index) file as _GMXMMPBSA_LIG.pdb
  File "/sansom/s152/bras4549/anaconda3/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/sansom/s152/bras4549/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 92, in gmxmmpbsa
    app.loadcheck_prmtops()
  File "/sansom/s152/bras4549/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 590, in loadcheck_prmtops
    maketop = CheckMakeTop(FILES, INPUT, self.external_progs)
  File "/sansom/s152/bras4549/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 99, in __init__
    self.checkPDB()
  File "/sansom/s152/bras4549/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 294, in checkPDB
    self.complex_str = parmed.read_PDB(self.complex_pdb)  # can always be initialized
  File "/sansom/s152/bras4549/anaconda3/lib/python3.8/site-packages/parmed/formats/pdb.py", line 376, in parse
    inst._parse_open_file(fileobj)
  File "/sansom/s152/bras4549/anaconda3/lib/python3.8/site-packages/parmed/formats/pdb.py", line 430, in _parse_open_file
    method_dispatch[rec](line)
  File "/sansom/s152/bras4549/anaconda3/lib/python3.8/site-packages/parmed/formats/pdb.py", line 703, in _end_model
    raise PDBError('Coordinate mismatch in model %d' % self._current_model_number)
PDBError: Coordinate mismatch in model 1
Exiting. All files have been retained.

**Comment by Valdes-Tresanco-MS** [comment] 2021-01-10 21:45
I think the error is related to the protein, which is a dimer.
We have not tested a system similar to this. Can you send me a sample of the files that you want to process? (tpr, 2-10 dynamic frames, mol2 ligand, index, etc.)


Regardless of this error, when you want to perform a protein-ligand (small molecule) analysis, you need to provide the ligand mol2 file.

**Comment by Valdes-Tresanco-MS** [comment] 2021-01-11 20:58
After reviewing and doing several tests, I realized that the problem is in the parmed module. GROMACS merges the chains into a single moleculetype. Any PDB file obtained from this topology will contain a single chain. This has the disadvantage that the chain can contain duplicate amino acids.`parmed` records this data according to atoms info (atom name, number, res name, chain, etc) as a key. In this case, `ALA 201` is in the two chains that you merged, so `parmed` will record this amino acid once but its coordinates twice. That's why it gives the error.

I will try some tests to see if it can solve this problem.

**Comment by Valdes-Tresanco-MS** [comment] 2021-01-13 17:34
Options:
- [ ] **renumber amino acids**. Avoid duplicates, it has the chains ids but makes analysis difficult.
- [ ] **add the chain identifier based on the structure**. Avoid duplicates, it has the chains ids, but it is difficult to assign identifiers in complex systems
- [ ] **use a reference structure**. It may be convenient to assign the chains ids, but it can be confusing.
- [ ] **chain ids defined by the user**. This is very complex, the result can be erratic.

**Closed** 2021-01-14 23:15 UTC
Labels: good first issue, third-party package bug
