### ISSUE TITLE
[Question]: CalcError: /usr/local/Amber18/bin/sander failed with prmtop complex.top!

### ISSUE THREAD

**Issue by eri-1994** [Valdes-Tresanco-MS/gmx_MMPBSA#367] opened 2023-05-02 18:40 UTC
### My Question is...

I'm trying to run de MMPBSA, but the job keeps failing with the following output:Loading and checking parameter files for compatibility... sander found! Using /usr/local/Amber18/bin/sander cpptraj found! Using /usr/local/Amber18/bin/cpptraj Preparing trajectories for simulation... 100 frames were processed by cpptraj for use in calculation.  Running calculations on normal system...  Beginning GB calculations with /usr/local/Amber18/bin/sander   calculating complex contribution...   File "/usr/local/Amber18/bin/MMPBSA.py", line 100, in <module>     app.run_mmpbsa()   File "/usr/local/Amber18/lib/python2.7/site-packages/MMPBSA_mods/main.py", line 218, in run_mmpbsa     self.calc_list.run(rank, self.stdout)   File "/usr/local/Amber18/lib/python2.7/site-packages/MMPBSA_mods/calculation.py", line 82, in run     calc.run(rank, stdout=stdout, stderr=stderr)   File "/usr/local/Amber18/lib/python2.7/site-packages/MMPBSA_mods/calculation.py", line 157, in run     self.prmtop)) CalcError: /usr/local/Amber18/bin/sander failed with prmtop complex.top! Exiting. All files have been retained.

**Comment by Valdes-Tresanco-MS** [comment] 2023-05-02 18:55
Although gmx_MMPBSA is based on it, we do not maintain MMPBSA.py. In any case, I will give you some guidance on the matter.
This error can be caused by many factors. The most common of which is setting `inp = 2.` In this case, sander tries to assign the radii of Tan, Yang & Luo to the system. If the system contains any molecule other than protein or nucleic acid, sander will fail. Checking the corresponding `*.mdout` file may give you a hint about it. Please consider contacting the developers of MMPBSA.py through the Amber mailing list if the error persists.
We are about to release native support for Amber, so stay tuned if you find it interesting to use all of the functionality that gmx_MMPBSA currently implements.

**Comment by Valdes-Tresanco-MS** [comment] 2023-05-04 05:34
Please, check this amber mailing list thread (http://archive.ambermd.org/201806/0167.html)
Please, consider posting/searching these problems in the amber mailing list. We don't develop, maintain or support MMPBSA.py.
I closed this issue since it is offtopic

**Closed by Valdes-Tresanco-MS** 2023-05-04 05:34 UTC
