### ISSUE TITLE
[Bug-gmx_MMPBSA]: Error in function returning the inconsistency warning

### ISSUE THREAD

**Issue by Ahmsame** [Valdes-Tresanco-MS/gmx_MMPBSA#217] opened 2022-04-15 22:44 UTC
### Bug summary

I get nothing written in the output file however the run seems to take all the time it needs. 

### Terminal output

```bash
I get this as the last line in my slurm file as I am running it on a supercomputer. 
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Error occurred on rank 0.
Exiting. All files have been retained.
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
```

### gmx_MMPBSA.log

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8498809/gmx_MMPBSA.log)

### Operating system

HPC linux based system 

### gmx_MMPBSA Version

gmx_MMPBSA v1.5.0.3

### Python version

Python 3.9.7

**Comment by marioernestovaldes** [comment] 2022-04-15 23:01
Please, check this [thread](https://groups.google.com/g/gmx_mmpbsa/c/tbH0AGdl7is/m/73dWsxy3AwAJ)... you can run gmx_MMPBSA using the --rewrite-output flag once you update the program:

`gmx_MMPBSA --rewrite-output`

let us know if that solves the problem...

cheers!

**Comment by Ahmsame** [comment] 2022-04-16 00:44
I will try it and keep you updated, however, I would like to know whether this warning Is normal or not! 
ib_md.c:1161 UCX  WARN  IB: ibv_fork_init() was disabled or failed, yet a fork() has been issued.
[1650069523.119334] [comp032:18553:0]          ib_md.c:1162 UCX  WARN  IB: data corruption might occur when using registered memory.
[progress.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8498991/progress.log)
as this upsets me!

**Comment by Valdes-Tresanco-MS** [comment] 2022-04-16 01:51
It seems similar to this [issue](https://github.com/h5py/h5py/issues/1079). We are thinking of removing the use of h5py since we have noticed that it has some performance issues with nested dictionaries as is our case.
We are sorry to hear about these issues. The problem is that our tests are on our PCs, so we have no way to identify these problems in HPC. Right now I am working on improving the performance of **gmx_MMPBSA_ana**, but as soon as I finish it I will work on removing h5py to see if the problem persists. I think it could also be related to the `platform.platform()` call that creates threads to get the values. If you want, you can try commenting out these lines and see if the warnings are not displayed.

https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/blob/59bff94de67fb2d2a7f9ce944860309231760150/GMXMMPBSA/utils.py#L702-L705

**Comment by marioernestovaldes** [comment] 2022-04-22 09:27
closing this... feel free to reopen if the issue persists...

**Closed by marioernestovaldes** 2022-04-22 09:27 UTC
Labels: bug
