### ISSUE TITLE
Problem in Residue Decomposition 

### ISSUE THREAD

**Issue by mtpae** [Valdes-Tresanco-MS/gmx_MMPBSA#101] opened 2021-12-08 11:05 UTC
Hello all, 
I have used the protein-ligand charm system for my MMPBSA analysis in that I am facing error in Residue Decomposition . The output file is not generated for per residue energy decomposition. 
I have attached the log file.
The command I used:
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7675513/gmx_MMPBSA.log)

**Comment by marioernestovaldes** [comment] 2021-12-08 12:25
Could you please share the file mmpbsa.txt you are using?

**Comment by mtpae** [comment] 2021-12-08 14:41
here it i
[mmpbsa.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7676733/mmpbsa.txt)
s

**Comment by Valdes-Tresanco-MS** [comment] 2021-12-08 16:19
The problem is that your input file does not contain the proper variables for what you want to do.

To perform a per-residue decomposition analysis, you must include the decomp namelist variables. See the documentation [here](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/input_file/#decomp-namelist-variables) and this [example](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/ examples/Decomposition_analysis/)

Additionally, you must carefully review the variables in the input file. When you use CHARMMff you don't need to define the `forcefield` variables in the input file. See [how gmx_MMPBSA works](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/howworks/#how-gmx_mmpbsa-works)

I close this issue. If you have any errors or doubts, feel free to open another issue. Check the [closed issues](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/issues?q=is%3Aissue+is%3Aclosed) and our [group](https://groups.google.com/g/gmx_mmpbsa) for frequent errors.

Cheers!
Mario S

**Closed by Valdes-Tresanco-MS** 2021-12-08 16:19 UTC
Labels: Inconsistent input files

**Comment by mtpae** [comment] 2021-12-09 09:51
Hello I have changed the files , now It shows the Decomposition energy output. But It shows the per residue binding energy in receptor only while Ligand's energy is not visible as per residue. as it is shown in Image ligand per residues energy is not visible in graph. My ligand is Peptide. 



![image](https://user-images.githubusercontent.com/92774704/145373567-94347e5a-e30f-47da-b725-11da1035ce1b.png)
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7683978/gmx_MMPBSA.log)
[mmpbsa.txt](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7683979/mmpbsa.txt)

**Comment by marioernestovaldes** [comment] 2021-12-09 10:21
you are using this command line 

`gmx_MMPBSA -i mmpbsa.txt -cs md_0_1.tpr -ci complex_index.ndx -cg 1 13 -ct md_0_1_fit50.xtc -cp topol.top -lm 1.mol2`

here you are using a mol2 file as input for your ligand (1.mol2) and gmx_MMPBSA interprets it as a small ligand rather than peptide... if the ligand has standard aminoacids there is no need to define a mol2 for it as the standard amber force field has parameters for it... 

cheers!

**Comment by mtpae** [comment] 2021-12-09 10:50
I have removed the -lm input option but still the result is same. I want Per residue decomposition of Ligand. I am attaching the Structure of ligand. 
[ligand.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7684408/ligand.zip)

**Comment by marioernestovaldes** [comment] 2021-12-09 11:22
The ligand doesn't seem to contain other elements different than the standard aminoacids... is there any particular reason why the ligand has this particular topology and structure files? is the ligand is a peptide and only contains standard aminoacids, it should has a format similar the that of the protein... unfortunately in this format is not possible to report the decomposition for the amioacids in the  ligand

**Comment by mtpae** [comment] 2021-12-09 11:34
Yes The ligand is a antiviral peptide and it doesn't have anything different than the standard amino acid.  Is there any other solution for it ?

**Comment by mtpae** [comment] 2021-12-09 11:35
Yes The ligand is an antiviral peptide and it doesn't have anything different than the standard amino acid. Is there any other solution for it ?

**Comment by marioernestovaldes** [comment] 2021-12-09 11:44
Well, the solution would be preparing a brand new system where you consider the ligand as it is, a protein type... If you are using charmm force field  you can use charmm-gui to prepare your system with just few clicks...
