### ISSUE TITLE
[Question]: EDISPER

### ISSUE THREAD

**Issue by chaninpark0806** [Valdes-Tresanco-MS/gmx_MMPBSA#381] opened 2023-06-07 01:57 UTC
### My Question is...

I upgraded from version 1.5.7 to 1.6.1, and one of the major differences is that all the values in the EDISPER category are now 0. Why is that?

**Comment by Valdes-Tresanco-MS** [comment] 2023-06-07 02:46
Sorry about that. We don't document it properly.
`inp = 2` is optimized for the radii of Tan, Yang & Luo, which is currently not applied in the program. With this value, sometimes high EDISPER values are obtained, so the energy is positive. To avoid this, in the latest versions, we decided to set inp=1 to avoid this problem. If you want to reproduce the results of version 1.5.7 set `inp=2` in the input file
Please, note you can get different values for the previous version (v1.5.7) with `inp=2` and this one (v1.6.1) with `inp=1`. If you can compare both calculations you set the same values for all parameters.

**Comment by chaninpark0806** [comment] 2023-06-07 08:58
Thank you for your response and efforts.

The entropy results for each frame in the FINAL_RESULTS_MMPBSA.csv file are missing.
How do I check in version 1.6.1?

**Comment by Valdes-Tresanco-MS** [comment] 2023-06-21 17:13
I am closing this issue since the initial question was solved

**Closed by Valdes-Tresanco-MS** 2023-06-21 17:13 UTC
