### ISSUE TITLE
[Question]: gmx_MMPBSA installation question

### ISSUE THREAD

**Issue by leiqian-nmsu** [Valdes-Tresanco-MS/gmx_MMPBSA#219] opened 2022-04-22 17:53 UTC
### My Question is...

Dear users, I plan to install gmx_MMPBSA using AmberTools compilation method. But I installed AmberTools without miniconda option (-DDOWNLOAD_MINICONDA=FALSE). Since I may need to use amber.python command later to install gmx_MMPBSA, so my question is without amber's inner miniconda, could I install gmx_MMPBSA successfully? Thanks!

**Comment by Valdes-Tresanco-MS** [comment] 2022-04-22 18:09
In principle, as long as the `python` you have used supports all the packages that AmberTools installs. Note that the minimum python version tested with **gmx_MMPBSA** was `3.8.x`.
In some cases, the installation of `mpi4py` fails when pip is used for installation. Let me know if you have any problems.

**Comment by leiqian-nmsu** [comment] 2022-04-24 16:05
@Valdes-Tresanco-MS Thank you for your kind reply. I tried my sys python (python3.8.10) to install it:
$ python -m pip install gmx_MMPBSA (so gmx_MMPBSA is installed in **~/.local/bin/gmx_MMPBSA**)
I ran the test command ($ gmx_MMPBSA_test -f ~/Downloads/ -n 5) , and so far no error shows up.
However, I notice in your web gmx_MMPBSA is installed inside ambertools/lib/python3/site-packages/GMMPBSA, so I wonder if my installation would cause any problem?
In addition, in gmx_MMPBSA_test/doc/examples/Proteins_ligand/MT (Multiple Traj), there are three trjectories (com, lig, rec all in water). Does gmx_MMPBSA support six traj case (adding com, lig, rec all in vaccum)? Thanks!

**Comment by Valdes-Tresanco-MS** [comment] 2022-04-24 18:36
> @Valdes-Tresanco-MS Thank you for your kind reply. I tried my sys python (python3.8.10) to install it: $ python -m pip install gmx_MMPBSA (so gmx_MMPBSA is installed in **~/.local/bin/gmx_MMPBSA**) I ran the test command ($ gmx_MMPBSA_test -f ~/Downloads/ -n 5) , and so far no error shows up. However, I notice in your web gmx_MMPBSA is installed inside ambertools/lib/python3/site-packages/GMMPBSA, so I wonder if my installation would cause any problem? 

As long as the AmberTools executables are available in the `PATH` and the dependencies are installed in this Python, there should be no problems. If **gmx_MMPBSA_test** works fine, then everything should work as expected. Note that if you `source amber.sh` that the `PYTHONPATH` variable may point to another Python libraries path. Make sure that variable is not defined or points to this python as well.

>In addition, in gmx_MMPBSA_test/doc/examples/Proteins_ligand/MT (Multiple Traj), there are three trjectories (com, lig, rec all in water). Does gmx_MMPBSA support six traj case (adding com, lig, rec all in vaccum)? Thanks!

**gmx_MMPBSA** generates temporary dry trajectories (named `COM_traj_0.xtc`, `REC_traj_0.xtc` and `LIG_traj_0.xtc` for example). If you already have such dry trajectories, then you can skip this step by setting the `solvated_trajectory = 0`. Note that you should not mix solvated and dry trajectories when `solvated_trajectory = 0`.

**Comment by leiqian-nmsu** [comment] 2022-04-27 17:09
@Valdes-Tresanco-MS Thank you! Although my PYTHONPATH points to .../amber20/lib/python3.8, which is different from my system python: /usr/bin/python3, but since I used my system python3 to build and install my amber20, so this setting might be OK. 
In addition, I tried to run the gmx_MMPBSA and noticed at the end of calculation a dialogue showed up and I had to do some operations on this interactive dialogue. Is it possible that I could skip this dialogue by setting every option clearly before it? 
Futhermore, in amber manual, it mentioned "a GPU-supported MMPBSA is under development.". Dose this mean gmx_MMPBSA currently is still CPU-driven? Thanks!

**Comment by leiqian-nmsu** [comment] 2022-04-30 17:02
@Valdes-Tresanco-MS Thank you again for your kind reply. Could I ask you a few new questions? thanks!
One week ago I installed gmx_MMPBSA on Ubuntu20.04 (ambertools20), it worked quite well.
Recently I tried to installed it on a different machine with Ubuntu18.04 (ambertools22). My questions are:
**(1)** I firstly installed most recent ambertools 22 on this Ubuntu18.04, and not sure if new ambertools version and old Ubuntu version may affect its installation.
**(2)** I just used command like previous (Not conda env) $ python -m pip install gmx_MMPBSA
But this time, I installed an old gmx_MMPBSA ($ gmx_MMPBSA --version)
gmx_MMPBSA v1.3.3 based on MMPBSA version 16.0 and AmberTools 20
Then I used the command to update it but cannot work: $ python -m pip install gmx_MMPBSA -U
(3) This old gmx_MMPBSA does not have gmx_MMPBSA_test command, and there is only [INFO ] header in its log file which is quite different from the detailed log file when I typed gmx_MMPBSA command on previsous machine. Actually this makes me confused and think it may not find ambertools in current machine.

**Comment by Valdes-Tresanco-MS** [comment] 2022-04-30 19:29
This is one of the problems of installing AmberTools with the system python. The problem is that the new versions explicitly specify `python 3.8` as a requirement. To avoid these problems, you should ideally install AmberTools with miniconda, either in the build or in a miniconda environment. This way, a version of python supported by **gmx_MMPBSA** will be installed. Ubuntu 18.04 has `python 3.6.x`

**gmx_MMPBSA** has evolved a lot from version `1.3.x` to `1.5.x`. We recommend always using the most recent versions. We are working to improve the compatibility of **gmx_MMPBSA_ana** with older versions (only with `1.4.x` and earlier versions of `1.5.x`). In this sense, the values obtained for the selected models do not change from one version to another. But you should note that some parameters have been modified, as well as others have been implemented and corrected. That is why some versions are not compatible with each other. 
Our recommendation is that you install everything using the conda environment with **AmberTools21** and **gmx_MMPBSA** from the development version (master branch - some performance problems of **gmx_MMPBSA_ana** have been fixed and are pending for the new version).
Yesterday we tested **AmberTools22**, but there seem to be some problems with the MPI. However, the changes are minor and not related to the programs used by **gmx_MMPBSA**. At the moment, I don't have much time to check this, so we will postpone it for next week.

**Comment by leiqian-nmsu** [comment] 2022-05-01 17:07
@Valdes-Tresanco-MS Thank you! I followed your advice. Because AmberTools21 is not available online now, I used my previous AmberTools20. I tried to install AmberTools20 on Ubuntu18.04 using options "-DDOWNLOAD_MINICONDA=TRUE -DMINICONDA_USE_PY3=TRUE". 
However, when I did $ ./run_cmake, I always got this error message: 
**CMake Error at cmake/PythonBuildConfig.cmake:129 (message):
  Failed to determine relative PYTHONPATH: python command failed with error
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  KeyError: 'unix_prefix'**
Actually because of this same error message last week I installed AmberTools20 on Ubuntu20.04 successfully using my system python3.8 instead of downloading miniconda.

**Comment by Valdes-Tresanco-MS** [comment] 2022-05-01 18:22
[Try installing AmberTools from conda-forge](https://valdes-tresanco-ms.github.io/gmx_MMPBSA/installation/#installing-gmx_mmpbsa-v150)
It is the easiest way, it does not generate incompatibility since it does not define the `PYTHONPATH` environment variable, it is isolated, so you can have simultaneously AmberTools 20, 21, and 22 installed if required and it is self-sufficient since conda has all the libraries it requires.

**Comment by leiqian-nmsu** [comment] 2022-05-02 13:32
@Valdes-Tresanco-MS Thanks! the easiest way works! I really appreciate it.

By the way, from my curiosity, when I installed AmberTools20 on Ubuntu18.04 with options "-DDOWNLOAD_MINICONDA=TRUE -DMINICONDA_USE_PY3=TRUE", the PYTHONPATH setting was supposed to be determined by the downloaded and installed miniconda in AmberTools' run_cmake process. That error "Failed to determine relative PYTHONPATH: python command failed with error" makes me confused.

**Comment by Valdes-Tresanco-MS** [comment] 2022-05-02 19:02
Do you have the `PYTHONPATH` variable defined? 
In the tests I did some time ago, I did not have this problem. According to the [CMake configuration for building with python](https://github.com/Amber-MD/cmake-buildscripts/blob/7efd69bcb2f1cd432fd0374c9b04b129e5b03577/PythonBuildConfig.cmake#L92-L129), it is a complicated and delicate process. My compatibility tests are always based on OS (Ubuntu 18.04 and 20.04, Centos7, Linux Mint 19.3 and 20.2, and Zorin OS 16 which is my OS) mostly freshly installed, so in many cases, these are previous configurations that conflict with the one required by the AmberTools installation. After going a long way in Python programming, I have realized that relying on the `PYTHONPATH` variable can be very problematic and from my point of view, a bad practice if it is not 100% necessary. That is why I recommend the use of miniconda which contains all the necessary dependencies and libraries so it avoids compatibility problems.

**Comment by leiqian-nmsu** [comment] 2022-05-04 12:11
@Valdes-Tresanco-MS Sorry for my late reply. Thank you for your advice. Actually, I do not have PYTHONPATH variable defined in my ~/.bashrc file. In my case, ambertools20 installation in ubuntu20 worked quite well without downloaded inner miniconda, but the PYTHONPATH error showed up again and again if I downloaded ambertools' own miniconda. From the link you sent to me I also noticed the author mentioned that "this was REALLY hard to figure out ..." Thanks again for your kind help! I think I should move on from this installation issue.

**Comment by Valdes-Tresanco-MS** [comment] 2022-05-04 18:32
I found the problem. `distutils` have changed since the AmberTools20 installer was created, so using the latest version of miniconda generates incompatibility. To solve the problem just change `unix_prefix` to `posix_prefix` on [line 101](https://github.com/Amber-MD/cmake-buildscripts/blob/7efd69bcb2f1cd432fd0374c9b04b129e5b03577/PythonBuildConfig.cmake#L101) of the `AmberTools20/amber20_src/cmake/PythonBuildConfig.cmake` file.

This way it worked for me. I recommend installing AmberTools from conda-forge unless you require the MPI compilation.
Let me know if works for you.

**Comment by leiqian-nmsu** [comment] 2022-05-05 11:56
@Valdes-Tresanco-MS Thank you for your advice! I will let you know if it works

**Comment by Valdes-Tresanco-MS** [comment] 2022-06-09 00:19
Closed due to inactivity. Feel free to reopen if necessary.

**Closed by Valdes-Tresanco-MS** 2022-06-09 00:19 UTC
Labels: installation

**Comment by leiqian-nmsu** [comment] 2022-08-29 09:43
Dear users, 
I tried to install gmx_MMPBSA using conda/pip in Centos.
After using command "$ screen" and then in screen I ran "$ conda activate gmxMMPBSA" and "$ conda install -c conda-forge mpi4py=3.1.3 ambertools=21.12 compilers -y -q", everything was OK and a comment "all requested packages already installed." showed up. 
However, I found two errors at the end: 
path_to_miniconda3/envs/gmxMMPBSA/etc/conda/deactivate.d/ambertools.sh:4: parse error near `]]`  
path_to_miniconda3/envs/gmxMMPBSA/etc/conda/activate.d/ambertools.sh:4: parse error near `]]` 
 
I am not sure if these two errors could be ignored or not. Thanks!
