### ISSUE TITLE
[Bug]: _GMXMMPBSA_COM.pdb Mistakenly renames the chains according to their orders in user's pdb

### ISSUE THREAD

**Issue by leiqian-nmsu** [Valdes-Tresanco-MS/gmx_MMPBSA#354] opened 2023-03-10 03:06 UTC
### Bug summary

Dear users, @Valdes-Tresanco-MS @marioernestovaldes
I found a bug when I used "&alanine_scanning" in mmpbsa.in, but I notice this bug might also be found in other cases.

For example, in my original pdb, the order of my chains is : H, L, A, B, C, D, E, F, G. Then after I ran gmxmmpbsa, the program automatically created a new pdb called _GMXMMPBSA_COM.pdb in which the chain names are completely different: A, B, C, D, E, F, G, H, I, although the position of each chain is still kept. (the name of H chain becomes A chain in new pdb file)

This bug caused error: If I mutate one residue (e.g. index 100) in H chain in my original pdb, then program may mutate the residue (index 100) in the H chain in _GMXMMPBSA_COM.pdb, but this H chain is actually F chain in my original pdb file.
Is it possible that this bug could be solved? Thanks!

### Terminal output

```bash
None
```

### gmx_MMPBSA.log

We couldn't find this residue CHAIN:H RES_NUM:100 ICODE:

### Operating system

Ubuntu

### Installation

None

**Comment by marioernestovaldes** [comment] 2023-03-10 03:19
Did you try defining a reference structure file with the -cr flag? In this case the reference structure will be the one containing the chain IDs that you defined previously...

**Comment by leiqian-nmsu** [comment] 2023-03-10 10:04
@marioernestovaldes 
Thank you very much for your reminding! I did not include this option, so the error happened.
I noticed _GMXMMPBSA_COM_FIXED.pdb fixed the wrong chain names in _GMXMMPBSA_COM.pdb.
I just found the "recommended" mark in your webpage, sorry for my carelessness.
Because this option is very important, is it possible it could be included in the Command-line example in the same webpage?

**Comment by marioernestovaldes** [comment] 2023-03-10 12:14
No need to apologize 🙂... It is a valid observation... For alanine scanning, yes! It could be really important  especially when the system have "non-continuos" chain IDs... I will include this in the tutorial asap. Thanks for your suggestion 🤓

**Comment by marioernestovaldes** [comment] 2023-03-10 14:53
updated docs https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/commit/8a3cf8d9a758e6899face6f6018937ecbcbcb6ca

closing issue...

**Comment by marioernestovaldes** [comment] 2023-03-10 16:54
> Thanks! @marioernestovaldes One more thing, for example, in FINAL_RESULTS_MMPBSA.dat, I found in the line "RESULTS OF ALANINE SCANNING (A/25 -VALXALA) the wrong chain name "A" (real chain name should be H) still shows up, although I added -cr flag and everything looks OK. Do you think it is a typo?

@Valdes-Tresanco-MS please check this...

**Comment by Valdes-Tresanco-MS** [comment] 2023-03-10 20:02
@leiqian-nmsu Can you send me the files to review and reproduce the problem? I think I experienced this problem at some point, but I can't reproduce it again. I think it was associated with editconf and trjconv, but I'm not sure. I will review it as soon as possible.

**Comment by leiqian-nmsu** [comment] 2023-03-12 08:26
@Valdes-Tresanco-MS 
Thanks! Please check your email: mariosergiovaldes145@gmail.com

**Comment by Valdes-Tresanco-MS** [comment] 2023-03-21 18:49
@leiqian-nmsu Can you test if it now works for you? 
In this case, you should install the development version
```bash 
python -m pip install git+https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA.git -U
```
and then run:
```bash
gmx_MMPBSA --rewrite-output
```

_Some reference notes._ The _GMXMMPBSA_COM.pdb file is generated using gmx editconf from the tpr. In this case, although the order is preserved, the names of the chains may be different (as in this case). We have experienced a few problems with this across the different versions of gromacs. On the other hand, _GMXMMPBSA_COM_FIXED.pdb corresponds to _GMXMMPBSA_COM.pdb after assigning the chain IDs. This is because in some versions of gromacs, sometimes the resulting pdb does not have a chain id, either because the tpr was generated from a gro file or because the gromacs version is old.

**Comment by leiqian-nmsu** [comment] 2023-03-22 17:04
@Valdes-Tresanco-MS 
Sure I will test it, thank you!
I tried to install a new gmxMMPBSA  env in conda using your recommended command.
(1) However, when I ran $ python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4, an error showed up: Collecting git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4
  Cloning https://github.com/Valdes-Tresanco-MS/ParmEd.git (to revision v3.4) to /tmp/pip-req-build-kqfbmpz9
  Running command git clone --filter=blob:none --quiet https://github.com/Valdes-Tresanco-MS/ParmEd.git /tmp/pip-req-build-kqfbmpz9
  fatal: unable to access 'https://github.com/Valdes-Tresanco-MS/ParmEd.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
  error: subprocess-exited-with-error
(2) In addition, I'd like to know if this update would change the dG or ddG results. It seems this update would correct the chain names in FINAL_RESULTS, but if the previous calculation was correct, it might not change the calculated results.

**Comment by Valdes-Tresanco-MS** [comment] 2023-03-22 17:23
> (1) However, when I ran $ python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4, an error showed up: Collecting git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4 Cloning https://github.com/Valdes-Tresanco-MS/ParmEd.git (to revision v3.4) to /tmp/pip-req-build-kqfbmpz9 Running command git clone --filter=blob:none --quiet https://github.com/Valdes-Tresanco-MS/ParmEd.git /tmp/pip-req-build-kqfbmpz9 fatal: unable to access 'https://github.com/Valdes-Tresanco-MS/ParmEd.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated. error: subprocess-exited-with-error

I've seen this sometimes happen, but it's not a repository issue. It could be a GitHub issue.
 
> (2) In addition, I'd like to know if this update would change the dG or ddG results. It seems this update would correct the chain names in FINAL_RESULTS, but if the previous calculation was correct, it might not change the calculated results.

No. The previous result is correct. As I explained in the reference notes, in this case, the chain ID was updated in the list of residues belonging to the receptor and the ligand according to the reference structure. This list is used to display text, not to define the mutant. The mutant is defined by index from _GMXMMPBSA_COM_FIXED.pdb, which already has all the correct information.

**Closed** 2023-11-07 18:46 UTC
Labels: bug
