### ISSUE TITLE
[Bug-gmx_MMPBSA]: ChangeRadiiError: You must choose from bondi, mbondi, mbondi2, mbondi3, amber6 radii sets

### ISSUE THREAD

**Issue by pauvalera** [Valdes-Tresanco-MS/gmx_MMPBSA#231] opened 2022-05-22 13:13 UTC
### Bug summary

We have encountered this error, PBRadii charmm_radii to Complex, even if we used charmm27 as the forcefield.

### Terminal output

```bash
aag32022@mmrl-04:~/PEGPCLtacrine_MMPBSA$ cat PEGPCLtacrine_MMPBSA.err
[INFO   ] Starting gmx_MMPBSA v1.5.2
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs sys.pdb -ci index.ndx -cg 2 3 -ct md_noPBC.xtc -cp topol.top -nogui

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /opt/amber/bin/cpptraj
[INFO   ] tleap found! Using /opt/amber/bin/tleap
[INFO   ] parmchk2 found! Using /opt/amber/bin/parmchk2
[INFO   ] sander found! Using /opt/amber/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /usr/local/gromacs-2021.4/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 2_3 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group 2 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group 3 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ]
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
[INFO   ] Detected CHARMM force field topology format...
[INFO   ] Assigning PBRadii charmm_radii to Complex...
  File "/home/aag32022/.local/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/aag32022/.local/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.make_prmtops()
  File "/home/aag32022/.local/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 538, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/aag32022/.local/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 118, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/home/aag32022/.local/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 474, in gmxtop2prmtop
    action = ChRad(com_amb_prm, PBRadii[self.INPUT['PBRadii']])
  File "/opt/amber/lib/python3.9/site-packages/parmed/tools/changeradii.py", line 293, in ChRad
    raise ChangeRadiiError("You must choose from %s radii sets" %
ChangeRadiiError: You must choose from bondi, mbondi, mbondi2, mbondi3, amber6 radii sets
Exiting. All files have been retained.
```

### gmx_MMPBSA.log

aag32022@mmrl-04:~/PEGPCLtacrine_MMPBSA$ cat PEGPCLtacrine_MMPBSA.err
[INFO   ] Starting gmx_MMPBSA v1.5.2
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs sys.pdb -ci index.ndx -cg 2 3 -ct md_noPBC.xtc -cp topol.top -nogui

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /opt/amber/bin/cpptraj
[INFO   ] tleap found! Using /opt/amber/bin/tleap
[INFO   ] parmchk2 found! Using /opt/amber/bin/parmchk2
[INFO   ] sander found! Using /opt/amber/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /usr/local/gromacs-2021.4/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 2_3 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group 2 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group 3 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ]
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
[INFO   ] Detected CHARMM force field topology format...
[INFO   ] Assigning PBRadii charmm_radii to Complex...
  File "/home/aag32022/.local/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/aag32022/.local/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.make_prmtops()
  File "/home/aag32022/.local/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 538, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/aag32022/.local/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 118, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/home/aag32022/.local/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 474, in gmxtop2prmtop
    action = ChRad(com_amb_prm, PBRadii[self.INPUT['PBRadii']])
  File "/opt/amber/lib/python3.9/site-packages/parmed/tools/changeradii.py", line 293, in ChRad
    raise ChangeRadiiError("You must choose from %s radii sets" %
ChangeRadiiError: You must choose from bondi, mbondi, mbondi2, mbondi3, amber6 radii sets
Exiting. All files have been retained.

**Comment by marioernestovaldes** [comment] 2022-05-22 16:08
Seems like the program is using an outdated parmed version. Did you install parmed from our repository?

python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4

**Comment by pauvalera** [comment] 2022-05-22 16:12
Hello! This is the ParmEd version that we have installed 
![Screenshot_20220523-000959_Slack](https://user-images.githubusercontent.com/106019855/169705057-a845d9bb-245d-4b2f-905f-5c089094d5c8.jpg)

**Comment by pauvalera** [comment] 2022-05-22 16:18
Even with this line installed, the same error appears:

python -m pip install git+https://github.com/ParmEd/ParmEd.git@16fb236



Is this one the correct command:
python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4

Thank you so much!

**Comment by Valdes-Tresanco-MS** [comment] 2022-05-22 16:45
> Is this one the correct command: python -m pip install git+https://github.com/Valdes-Tresanco-MS/ParmEd.git@v3.4

Did this command line solve your problem?

**Comment by pauvalera** [comment] 2022-05-23 00:24
hello! we have installed this in our system already 
![image](https://user-images.githubusercontent.com/106019855/169722919-bb04a846-6fbc-44de-b92b-17f334be7107.png)

**Comment by pauvalera** [comment] 2022-05-23 00:24
however, the same error keeps popping up

[INFO   ] Starting gmx_MMPBSA v1.5.2
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs sys.pdb -ci index.ndx -cg 2 3 -ct md_noPBC.xtc -cp topol.top -nogui

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /opt/amber/bin/cpptraj
[INFO   ] tleap found! Using /opt/amber/bin/tleap
[INFO   ] parmchk2 found! Using /opt/amber/bin/parmchk2
[INFO   ] sander found! Using /opt/amber/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /usr/local/gromacs-2021.4/bin/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 2_3 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group 2 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group 3 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ] 
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
[INFO   ] Detected CHARMM force field topology format...
[INFO   ] Assigning PBRadii charmm_radii to Complex...
  File "/home/aag32022/.local/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/aag32022/.local/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.make_prmtops()
  File "/home/aag32022/.local/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 538, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/aag32022/.local/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 118, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/home/aag32022/.local/lib/python3.8/site-packages/GMXMMPBSA/make_top.py", line 474, in gmxtop2prmtop
    action = ChRad(com_amb_prm, PBRadii[self.INPUT['PBRadii']])
  File "/opt/amber/lib/python3.9/site-packages/parmed/tools/changeradii.py", line 293, in ChRad
    raise ChangeRadiiError("You must choose from %s radii sets" %
ChangeRadiiError: You must choose from bondi, mbondi, mbondi2, mbondi3, amber6 radii sets
Exiting. All files have been retained.

**Comment by Valdes-Tresanco-MS** [comment] 2022-05-23 02:35
Please, attach the gmx_MMMPBSA.log file (Don't copy the content here)

**Comment by Valdes-Tresanco-MS** [comment] 2022-05-23 02:47
Now that I check, the problem is that you are using two different pythons.

`"/home/aag32022/.local/lib/python3.8/site-packages/GMXMMPBSA/app.py"`
and 
`"/opt/amber/lib/python3.9/site-packages/parmed/tools/changeradii.py"`

This happens because you installed gmx_MMPBSA presumably with the system python and in addition, you have the one installed with the AmberTools compilation.
When you source amber.sh the PYTHONPATH variable is exported, making it so that all python interpreters can search packages in that path.
If you use **gmx_MMPBSA** with an Ambertools compilation, you must use amber.python. In any case, we recommend using conda environments to avoid these problems.

You can check [this thread](https://groups.google.com/g/gmx_mmpbsa/c/ZxPZc3CQTow/m/trKQN9UvDQAJ) where I explain the steps to follow to reinstall **gmx_MMPBSA**

**Comment by pauvalera** [comment] 2022-05-23 02:51
here are the file asked
[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8751119/gmx_MMPBSA.log)

**Comment by marioernestovaldes** [comment] 2022-05-30 21:20
closing this issue... feel free to reopen if there is any other error...

**Closed by marioernestovaldes** 2022-05-30 21:20 UTC
Labels: installation, old-parmed
