### ISSUE TITLE
[Question]: Would this work on a system containing Boron?

### ISSUE THREAD

**Issue by jssantiagojr** [Valdes-Tresanco-MS/gmx_MMPBSA#215] opened 2022-04-09 10:48 UTC
### My Question is...

Hi!

I reconstructed my system's( containing Boron) topology parameters to be in line with Charmm. I'm also using a custom forcefield( got it from a paper) that incorporates Boron.

Would there be a problem in the program when it converts these to Amber topology? Are there files I have to edit to account for these? 

Thank you!

**Comment by marioernestovaldes** [comment] 2022-04-09 11:41
If you define the topology with the -cp flag as recommended for systems prepared with charmm force field (https://valdes-tresanco-ms.github.io/gmx_MMPBSA/examples/Protein_ligand_CHARMMff/), everything should run smoothly... Have a go a let us know how it goes...

Cheers!

**Comment by jssantiago3** [comment] 2022-04-10 12:18
hmmm it seems I'm still getting errors with the angles. I'm getting the following error.
[INFO   ] Building Normal Complex Amber topology...
  File "/home/josh/miniconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/josh/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.make_prmtops()
  File "/home/josh/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 538, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/josh/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 118, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/home/josh/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 442, in gmxtop2prmtop
    com_top = self.cleantop(self.FILES.complex_top, self.indexes['COM']['COM'])
  File "/home/josh/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 716, in cleantop
    rtemp_top = parmed.gromacs.GromacsTopologyFile(ttp_file.as_posix())
  File "/home/josh/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 251, in __init__
    self.read(fname, defines, parametrize)
  File "/home/josh/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 326, in read
    ang, ub, angt, ubt = self._parse_angles(line, angle_types, ub_types,
  File "/home/josh/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 553, in _parse_angles
    i, j, k = [int(w)-1 for w in words[:3]]
  File "/home/josh/miniconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 553, in <listcomp>
    i, j, k = [int(w)-1 for w in words[:3]]
ValueError: invalid literal for int() with base 10: '#ifdef'

**Comment by marioernestovaldes** [comment] 2022-04-10 14:55
Something seems to be missplaced in the topology... Could you please send the topology with all the associated folders and .itp files!?

**Comment by jssantiago3** [comment] 2022-04-10 15:13
[topologyfiles.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/8459288/topologyfiles.zip)
here are my files!

**Comment by Valdes-Tresanco-MS** [comment] 2022-04-10 15:59
The problem is even funny. The directives (`# as first character`) as well as the topology sections should be left justified. Your topology has text formatting problems. That is, it currently appears like this: 
```
; Include water topology
#include "./hBN_charmm27.ff/tip3p.itp"


 #ifdef POSRES_WATER
 ; Position restraint for each water oxygen
 [ position_restraints ]
 ;  i funct       fcx        fcy        fcz
    1    1       1000       1000       1000
 #endif
 ; Include topology for ions
 #include "./hBN_charmm27.ff/ions.itp"

  [ system ]
; Name in water
  SAPS in water

  [ molecules ]
  ; Compound        #mols
SAP             1
AFB1_best             1
SOL         10348
NA               20
CL               20
```
includes one space before the `#ifdef` and `#endif` directives and two before `[ system ]` and `[ molecules ]` sections


and it must be to appear like this:
```
; Include water topology
#include "./hBN_charmm27.ff/tip3p.itp"

#ifdef POSRES_WATER
 ; Position restraint for each water oxygen
 [ position_restraints ]
 ;  i funct       fcx        fcy        fcz
    1    1       1000       1000       1000
#endif

; Include topology for ions
#include "./hBN_charmm27.ff/ions.itp"

[ system ]
; Name in water
  SAPS in water

[ molecules ]
; Compound        #mols
SAP             1
AFB1_best             1
SOL         10348
NA               20
CL               20
```

After fixing the formatting, it works as expected.
Let me know if this solve the problem.
Cheers!
Mario S.

**Comment by jssantiago3** [comment] 2022-04-10 16:06
yup it's running now! I'll let you know if I encounter anything. 

I never would've guessed that was the problem! I was racking my brain on somehow having errors in values under [ angles ]
Thanks!

**Comment by Valdes-Tresanco-MS** [comment] 2022-04-10 16:12
No problem, that happens often. Don't worry, that's what we're here for. As I saw, the text format of that topology is a disaster, so you should check, at least, the remarks that I made above.
I close this issue. Feel free to open a new one if you have problems.

**Closed by Valdes-Tresanco-MS** 2022-04-10 16:12 UTC
