### ISSUE TITLE
gmx_MMPBSA error on running CHARMMff examples

### ISSUE THREAD

**Issue by yjwang-szbl** [Valdes-Tresanco-MS/gmx_MMPBSA#83] opened 2021-10-01 09:14 UTC
I installed Ambertools21 and gmx_MMPBSA v1.4.3 on Unbutu 18.04. The test runs on amberff examples work fine, but the tests on CHARMMff examples reported weird errors.

As detailed in error_V0001.log, the error is on reading the version stamp in COM.prmtop .
"""
At line 170 of file /home/szbl/soft/amber20_src/AmberTools/src/lib/nxtsec.F
Fortran runtime error: Bad value during floating point read
Error termination. Backtrace:
#0  0x7f92ff5afea7 in ???
#1  0x7f92ff5b0a45 in ???
#2  0x7f92ff5b11fc in ???
#3  0x7f92ff67b6ae in ???
#4  0x7f92ff67e7f4 in ???
#5  0x55d7daff15e0 in ???
#6  0x55d7daff1193 in ???
#7  0x55d7dad0ede1 in ???
#8  0x55d7dacf3cd0 in ???
#9  0x55d7dacf2d32 in ???
#10  0x55d7dacf2d8e in ???
#11  0x7f92fefacbf6 in ???
#12  0x55d7dab4ad19 in ???
#13  0xffffffffffffffff in ???
  File "/home/szbl/anaconda3/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/szbl/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 98, in gmxmmpbsa
    app.run_mmpbsa()
  File "/home/szbl/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 209, in run_mmpbsa
    self.calc_list.run(rank, self.stdout)
  File "/home/szbl/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/calculation.py", line 84, in run
    calc.run(rank, stdout=stdout, stderr=stderr)
  File "/home/szbl/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/calculation.py", line 158, in run
    raise CalcError('%s failed with prmtop %s!' % (self.program,
CalcError: /home/szbl/soft/amber20/bin/sander failed with prmtop COM.prmtop!
Exiting. All files have been retained.
"""

This error can be solved if I changed the amberformat.py (line 813) by setting VERSION_STAMP = V0001.000 to VERSION_STAMP = V00001.000 , yet another error appears as detailed in error_V00001.log, 

"""
  File "/home/szbl/anaconda3/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/szbl/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/app.py", line 107, in gmxmmpbsa
    app.parse_output_files()
  File "/home/szbl/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/main.py", line 1060, in parse_output_files
    self.calc_types[key]['delta'] = BindClass(
  File "/home/szbl/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/amber_outputs.py", line 1069, in __init__
    self.delta2()
  File "/home/szbl/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/amber_outputs.py", line 1294, in delta2
    self.com.fill_composite_terms()
  File "/home/szbl/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/amber_outputs.py", line 370, in fill_composite_terms
    self.data[component] = self.data[key] + self.data[component]
  File "/home/szbl/anaconda3/lib/python3.8/site-packages/GMXMMPBSA/amber_outputs.py", line 59, in __add__
    raise LengthError('length mismatch in energy vectors')
LengthError: length mismatch in energy vectors
Exiting. All files have been retained.
""""
It seems to me that the internal converstion between CHARMMff top to AMBER top is problematic. Any suggestions on solving this issues? 

Thank you very much.

BTW, my posts are automatically deleted in the Google Group. That is why I have to post here.
  
Best,

Yingjie

[error_V0001.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7265748/error_V0001.log)
[error_V00001.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7265750/error_V00001.log)

**Comment by Valdes-Tresanco-MS** [comment] 2021-10-01 15:29
Apparently, Google interprets your email as spam and after approving the publications, they disappeared ... Sorry for that ...

**Comment by yjwang-szbl** [comment] 2021-10-02 02:38
Hi Mario,

Thank you for your help. The examples I used are just the standard examples provided in the docs folder, including Protein_ligand_CHARMMff, Protein_membranme_CHARMMff etc. Given your input, I realized that the problem might be on my local installation of gromacs, which provides CHARMM topology for running these examples.  I will further check these details and let you know the progress.

Thanks,

Yingjie


------------------------------------------------------------------
发件人：Mario Sergio Valdés Tresanco ***@***.***>
发送时间：2021年10月1日(星期五) 23:24
收件人：Valdes-Tresanco-MS/gmx_MMPBSA ***@***.***>
抄　送：王英杰 ***@***.***>; Author ***@***.***>
主　题：Re: [Valdes-Tresanco-MS/gmx_MMPBSA] gmx_MMPBSA error on running CHARMMff examples (#83)

Hi Yingjie.
I have never seen this error and according to your description, it seems to be a problem with the structure of the input topology, that is, an unsupported version of CHARMM.
 I cannot reproduce this error. If you can send me the files (*.ndx, *.trp, 10 frames *.xtc, *.top with all dependencies [top folder and *.prm], and the groups) to try to reproduce it.
Cheers!
 Mario S
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Valdes-Tresanco-MS** [comment] 2021-10-06 20:15
Hi Yingjie
Have you made progress in discovering the reason for the problem?
I have not been able to reproduce it.
I agree with you that it may be due to the charmmff in the GROMACS directory since our examples work with such content.
Have you tried with a system prepared in CHARMM-GUI?

**Comment by Valdes-Tresanco-MS** [comment] 2021-10-08 16:22
I attach the example solved with CHARMM ff.
Please keep me aware of the problem.

Cheers!
Mario S.

[Protein_ligand_CHARMMff.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/7312801/Protein_ligand_CHARMMff.zip)

**Comment by yjwang-szbl** [comment] 2021-10-09 04:58
Hi Mario,

I compared your intermediate files with my local files, and found no difference in the prmtop files. With your files, I directly used MMPBSA.py for calculation and yielded same errors. So it turns out my previous installation of AmberTool21 might have some bugs in processing these topolgy files and running calculations. I am not aware whether this bug is specific to my installation, although the installation follows the official guide.

I have reinstalled AmberTool20 and gmx_MMPBSA following the exact same procedure as installing AmberTool21, and now everything works fine. 

Thanks for your help. 

Best,

Yingjie


------------------------------------------------------------------
发件人：Mario Sergio Valdés Tresanco ***@***.***>
发送时间：2021年10月9日(星期六) 00:22
收件人：Valdes-Tresanco-MS/gmx_MMPBSA ***@***.***>
抄　送：王英杰 ***@***.***>; Author ***@***.***>
主　题：Re: [Valdes-Tresanco-MS/gmx_MMPBSA] gmx_MMPBSA error on running CHARMMff examples (#83)

I attach the example solved with CHARMM ff.
 Please keep me aware of the problem.
Cheers!
 Mario S.
Protein_ligand_CHARMMff.zip
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Valdes-Tresanco-MS** [comment] 2021-10-09 05:23
Excellent.
I was going to recommend reinstalling Ambertools, but it got ahead of me.

I close this issue now. If you have another error, please open a new issue

Cheers!
Mario S.

**Closed by Valdes-Tresanco-MS** 2021-10-09 05:23 UTC
