### ISSUE TITLE
[Bug-gmx_MMPBSA]: ParmEd ValueError when building Normal Complex Amber topology

### ISSUE THREAD

**Issue by patochinestrad** [Valdes-Tresanco-MS/gmx_MMPBSA#283] opened 2022-08-20 22:23 UTC
### Bug summary

gmx_MMPBSA runs without issue until the "Building Normal Complex Amber topology" step, before exiting due to a ValueError from ParmEd.

### Terminal output

```bash
gmx_MMPBSA -O -i mmpbsa.in -cs md_0_10.tpr -ci index.ndx -cg 22 14 -ct IDO1_C8_fit.xtc -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv
[INFO   ] Starting gmx_MMPBSA v1.5.6
[INFO   ] Command-line
  gmx_MMPBSA -O -i mmpbsa.in -cs md_0_10.tpr -ci index.ndx -cg 22 14 -ct IDO1_C8_fit.xtc -cp topol.top -o FINAL_RESULTS_MMPBSA.dat -eo FINAL_RESULTS_MMPBSA.csv

[INFO   ] Checking mmpbsa.in input file...
[INFO   ] Checking mmpbsa.in input file...Done.

[INFO   ] Checking external programs...
[INFO   ] cpptraj found! Using /home/pato/anaconda3/envs/gmxMMPBSA/bin/cpptraj
[INFO   ] tleap found! Using /home/pato/anaconda3/envs/gmxMMPBSA/bin/tleap
[INFO   ] parmchk2 found! Using /home/pato/anaconda3/envs/gmxMMPBSA/bin/parmchk2
[INFO   ] sander found! Using /home/pato/anaconda3/envs/gmxMMPBSA/bin/sander
[INFO   ] Using GROMACS version > 5.x.x!
[INFO   ] gmx found! Using /home/pato/anaconda3/envs/gmxMMPBSA/bin.AVX2_256/gmx
[INFO   ] Checking external programs...Done.

[INFO   ] Building AMBER topologies from GROMACS files...
[INFO   ] Get PDB files from GROMACS structures files...
[INFO   ] Making gmx_MMPBSA index for complex...
[INFO   ] Normal Complex: Saving group 22_14 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_COM.pdb
[INFO   ] No receptor structure file was defined. Using ST approach...
[INFO   ] Using receptor structure from complex to generate AMBER topology
[INFO   ] Normal Receptor: Saving group 22 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_REC.pdb
[INFO   ] No ligand structure file was defined. Using ST approach...
[INFO   ] Using ligand structure from complex to generate AMBER topology
[INFO   ] Normal Ligand: Saving group 14 in _GMXMMPBSA_COM_index.ndx file as _GMXMMPBSA_LIG.pdb
[INFO   ] Checking the structures consistency...
[INFO   ]
[INFO   ] Using topology conversion. Setting radiopt = 0...
[INFO   ] Building Normal Complex Amber topology...
  File "/home/pato/anaconda3/envs/gmxMMPBSA/bin/gmx_MMPBSA", line 8, in <module>
    sys.exit(gmxmmpbsa())
  File "/home/pato/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/app.py", line 101, in gmxmmpbsa
    app.make_prmtops()
  File "/home/pato/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/main.py", line 537, in make_prmtops
    self.FILES.mutant_receptor_prmtop, self.FILES.mutant_ligand_prmtop) = maketop.buildTopology()
  File "/home/pato/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 118, in buildTopology
    tops = self.gmxtop2prmtop()
  File "/home/pato/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 461, in gmxtop2prmtop
    com_top = self.cleantop(self.FILES.complex_top, self.indexes['COM']['COM'])
  File "/home/pato/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/GMXMMPBSA/make_top.py", line 748, in cleantop
    rtemp_top = parmed.gromacs.GromacsTopologyFile(ttp_file.as_posix())
  File "/home/pato/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 251, in __init__
    self.read(fname, defines, parametrize)
  File "/home/pato/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/parmed/gromacs/gromacstop.py", line 357, in read
    name, num = line.split()
ValueError: too many values to unpack (expected 2)
Exiting. All files have been retained.
```

### gmx_MMPBSA.log

[gmx_MMPBSA.log](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/9388069/gmx_MMPBSA.log)

### Operating system

WSL - Ubuntu 20.04

### gmx_MMPBSA Version

gmx_MMPBSA v1.5.6 based on MMPBSA version 16.0 and AmberTools 20

### Python version

Python 3.9.13

### Installation

conda AmberTools + conda

**Comment by Valdes-Tresanco-MS** [comment] 2022-08-20 22:27
It seems to be a topology problem, could you please send your files to check them?

**Comment by patochinestrad** [comment] 2022-08-20 23:00
Of course, here are the files used for the run. I included a 10-frames .xtc instead of the original.

[files.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/9388108/files.zip)

**Comment by Valdes-Tresanco-MS** [comment] 2022-08-20 23:11
Please, include the charmm36-jul2021.ff folder and *.prm files

**Comment by Valdes-Tresanco-MS** [comment] 2022-08-20 23:15
I think the problem is in line 54 of the topology file. It seems like an incorrect notation for SOL molecules.
```
[ molecules ]
; Compound        #mols
Protein_chain_P     1
Other_chain_H       1
CD8                 1SOL             16597
SOL         16584
SOD              2
```

**Comment by patochinestrad** [comment] 2022-08-20 23:29
I removed the wrong line in the topology file and tried running the software again. The issue didn't happen this time and the program is now running. I'll update if the problem is solved or if there is another issue. 
[charmm_prm_itps.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/9388130/charmm_prm_itps.zip)

However, here are the force field folder and files you requested.

Thank you very much for your help and swift answer, Mario!
[charmm_prm_itps.zip](https://github.com/Valdes-Tresanco-MS/gmx_MMPBSA/files/9388131/charmm_prm_itps.zip)

**Comment by Valdes-Tresanco-MS** [comment] 2022-08-20 23:38
I will close the issue. If you have an error in the calculation, please open a new one so we can better follow up.

**Closed by Valdes-Tresanco-MS** 2022-08-20 23:38 UTC
